tbccsi \
  --sample-id   SH_8_Pre \
  --input-slide "slides/SH-8 Pre/SH-8 Pre.svs" \
  --tile-file   results/SH_8_Pre/common_tiling.csv \
  --output-dir  results/SH_8_Pre/ \
  --models      models/mixed_224_c/model_dir \
  --models      models/mixed_224_i/model_dir \
  --models      models/mixed_224_s/model_dir \
  --models      models/mixed_imm_m_224/model_dir \
  --models      models/mixed_imm_t_224/model_dir \
  --prefixes    cancer \
  --prefixes    immune \
  --prefixes    stroma \
  --prefixes    macs \
  --prefixes    tcells \
  --batch-size  264 \
  --save-h-and-e-tiles \
  --save-segmented-tiles